
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import localFont from "next/font/local";
import Header from "../components/header";
import Footer from "../components/footer";
import AuthProvider from "@/Context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const Helvetica = localFont({
  src: "./fonts/Helvetica.woff",
  variable: "--font-helvetica",
  weight: "100 900",
});
const HelveticaBold = localFont({
  src: "./fonts/Helvetica-Bold.woff",
  variable: "--font-helvetica-bold",
  weight: "100 900",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const noLayoutPages = ["/signin", "/signup"];

  return (
    <html lang="en">
       <AuthProvider>
      <body className={`${inter.className} ${Helvetica.variable } ${HelveticaBold.variable}`  } >
          {/* {!noLayoutPages.includes(pathname) && <Header />} */}
          <Header />
        {children}
       
        {/* {!noLayoutPages.includes(pathname) && <Footer />} */}
        <Footer />
        </body>
        </AuthProvider>
    </html>
  );
}
